---
deployment:
  tasks:
    - export DEPLOYPATH=/home/monkcdmb/public_html/
    - /bin/cp fetch_new_recording.php $DEPLOYPATH
    - /bin/cp fetch_pieces.php $DEPLOYPATH
    - /bin/cp fetchinstruments_data.php $DEPLOYPATH
    - /bin/cp fetchrecordings_data.php $DEPLOYPATH
    - /bin/cp get_monkeywrench_metric_arr.php $DEPLOYPATH
    - /bin/cp get_new_instrument_data.php $DEPLOYPATH
    - /bin/cp get_preload.php $DEPLOYPATH
    - /bin/cp get_recording_instruments.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp mysql-metric-arr-submit.php $DEPLOYPATH
    - /bin/cp phpinfo.php $DEPLOYPATH
    - /bin/cp removetime.py $DEPLOYPATH
    - /bin/cp stripped-synpdf-extras.js $DEPLOYPATH
    - /bin/cp stripped-synpdf-styles.css $DEPLOYPATH
    - /bin/cp stripped-synpdf.js $DEPLOYPATH
    - /bin/cp check_multiple_parts.php $DEPLOYPATH

    - export DEPLOYPATH2=/home/monkcdmb/phpfiles/
    - /bin/cp phpfiles/composers-addnew.php $DEPLOYPATH2
    - /bin/cp phpfiles/get_pieces_and_composers.php $DEPLOYPATH2
    - /bin/cp phpfiles/metric-arr-post.php $DEPLOYPATH2
    - /bin/cp phpfiles/pieces-addnew.php $DEPLOYPATH2
    - /bin/cp phpfiles/submit_recording.php $DEPLOYPATH2

    - export DEPLOYPATH3=/home/monkcdmb/public_html/editmode/
    - /bin/cp synpdf_182/editmode/synpdf-edit-mode.php $DEPLOYPATH3 
    - /bin/cp synpdf_182/editmode/edit-mode-tools.js $DEPLOYPATH3
    - /bin/cp synpdf_182/editmode/synpdf-edit-mode.js $DEPLOYPATH3
    - /bin/cp synpdf_182/editmode/dispatcher.php $DEPLOYPATH3
    - /bin/cp synpdf_182/editmode/load_file.php $DEPLOYPATH3
    - /bin/cp synpdf_182/editmode/get_recordings_already_synced.php $DEPLOYPATH3

    - export DEPLOYPATH4=/home/monkcdmb/public_html/editmode-loadfiles/
    - /bin/cp -r synpdf_182/editmode-loadfiles/ $DEPLOYPATH2
